### PR TITLE
Add keyboard teleoperation

### LINKED ISSUE #50: Add keyboard teleoperation
Use this as an example https://github.com/AndriyPt/ros-navigation-examples/blob/kinetic-devel/moon_control/launch/teleop.launch

### PR DESCRIPTION
**Pull request by MaxZhaloba**
Closes #50 

@AndriyPt, when I manually start the simulation.launch and control.launch I'm able to control the robot from keyboard, but it works not very smoothly and responsively. Please review my code and let me know if any improvements are necessary.

### CODE REVIEW

**Comment by MaxZhaloba** [comment]
@AndriyPt, when I manually start the simulation.launch and control.launch I'm able to control the robot from keyboard, but it works not very smoothly and responsively. Please review and let me know if any improvements are necessary.

**Comment by MaxZhaloba** [comment]
Sorry for the branch name :) I've just noticed it.

**Comment by AndriyPt** [comment]
@MaxZhaloba there is no need to run control.launch since simulation.launch is starting it :)

**Review by AndriyPt — CHANGES_REQUESTED** [review]
Robot is driving into opposite direction. Pressing I should move robot forward but it is moving robot backward :)

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
