### PR TITLE
F#188 add block diagram

### LINKED ISSUE #118: Create block diagram of robot's electronics

### PR DESCRIPTION
**Pull request by vyosypenko**
Closes #118

### CODE REVIEW

**Comment by AndriyPt** [comment]
@nemo8 few remarks:
- Your usage of GitHub closing keywords in PR is not correct. Please check the document https://help.github.com/articles/closing-issues-using-keywords/
- It might be good idea to create markdown document and put there links to datasheet instead of putting them into documentations. Since license of these files might permit to do it.

**Comment by vyosypenko** [comment]
Closes#118

**Comment by AndriyPt** [comment]
@nemo8 there should be space between closes and number of the issue :)

**Review by AndriyPt — APPROVED** [review]

**Comment by vyosypenko** [comment]
@AndriyPt, thanks a lot. Lesson learned. 
P.S. It was my first "pull request"

**Comment by AndriyPt** [comment]
@nemo8 congratulations, it was merged :+1:

**Pull request merged**
