### PR TITLE
F#53 add navigation stack

### PR DESCRIPTION
**Pull request by LyubomyrD**
@AndriyPt  I am not sure if it is ready to merge, but I would like to ask You to give it a try and say Your comments afterwards, please.
Is it just a matter of tuning the parameters?

### CODE REVIEW

**Comment by AndriyPt** [comment]
Is robot able to plan and move to any point in the building?

**Comment by AndriyPt** [comment]
Map is really "small" 
image

**Comment by LyubomyrD** [comment]
@AndriyPt  Well, the robot is able to,  but he is doing this slowly since the amount of computation is quite significant for him right now. I will fix this tuning the parameters.

**Comment by LyubomyrD** [comment]
@AndriyPt The map is small since the robot is moving only forward a backward. Is it possible to navigate through the map, while gmapping, before teleoperation is added?

**Comment by AndriyPt** [comment]
@LyubomyrD of course. Please start 
```bash
rqt 
```
Go to menu **Plugins** => **Robot Tools** => **Robot Steering**
Put correct topic name `/leobot/wheel_diff_drive_controller/cmd_vel` 
It should look like this:
image
Use arrows to control robot :)

**Comment by LyubomyrD** [comment]
@AndriyPt  Cool! Thanks :)

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
